"""Added one more column and one index

Revision ID: c3d7159fe22e
Revises: 
Create Date: 2024-12-28 14:09:31.943490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d7159fe22e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gang_members', sa.Column('weight', sa.DECIMAL(), nullable=True))
    op.create_index('ix_nickname', 'gang_members', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nickname', table_name='gang_members')
    op.drop_column('gang_members', 'weight')
    # ### end Alembic commands ###
